import dash_elasticsearch_autosuggest
import dash
import dash_core_components as dcc
from dash.dependencies import Input, Output
import dash_html_components as html

app = dash.Dash(__name__)

app.scripts.config.serve_locally = True
app.css.config.serve_locally = True

fields=["AAPL", "AMZN", "GOOGL", "MSFT", "original", "normalized"]
suggestions = ["valid", "options", "as", "suggestions"]; # generated by, i.e. query to db

app.layout = html.Div([
	html.Datalist(
	    id='list-suggested-inputs', 
	    children=[html.Option(value=word) for word in fields]
	),
	dcc.Input(id='input',
	    type='text',
	    list='list-suggested-inputs',
        placeholder='Enter a Stock Symbol',
	    value=''
	),
    html.Div(id='output')
])

@app.callback(Output('output', 'children'), [Input('input', 'value')])
def display_output(value):
    return 'You have entered {}'.format(value)


if __name__ == '__main__':
    app.run_server(debug=False)

